modLoader="javafml"
loaderVersion="[32,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/InfinityMending/issues"
[[mods]]
modId="infinitymending"
version="0.1.0"
displayName="InfinityMending"
displayURL="https://github.com/PieKing1215/InfinityMending"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you combine Infinity and Mending.'''

[[dependencies.infinitymending]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitymending]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"