modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL=""
[[mods]]
modId="infinitymending"
version="0.1.0"
displayName="InfinityMending"
#displayURL=""
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you combine Infinity and Mending.'''

[[dependencies.infinitymending]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitymending]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"