modLoader="javafml"
loaderVersion="[37,)"
license="LGPL v3.0"
#issueTrackerURL=""
[[mods]]
modId="infinitymending"
version="0.1.0"
displayName="InfinityMending"
#displayURL=""
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Lets you combine Infinity and Mending.'''

[[dependencies.infinitymending]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitymending]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,]"
    ordering="NONE"
    side="BOTH"